name: Changelog

on:
  push:
    tags:
      - "v*"

jobs:
  tagged-release:
    name: Changelog
    runs-on: ubuntu-latest
    # needs: release

    permissions:
          id-token: "write"
          contents: "write"
          packages: "write"
          pull-requests: "read"

    steps:
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ github.token }}"
          prerelease: false
