name: Native Integration Tests 2

on:
  push:
  pull_request:

jobs:
  build-ios-test-dev-container:
    name: Build iOS RN Test App (Dev)
    uses: ./.github/workflows/build-ios-test-container-app.yml
    secrets: inherit
    permissions:
      contents: read
      pull-requests: read
    with:
      configuration: Debug
